name: Deploy HTML File

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Configure EC2 instance
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo apt-get update
            if ! command -v apache2 &> /dev/null
            then
              echo "Apache no está instalado. Instalando Apache..."
              sudo apt-get install -y apache2
              sudo systemctl enable apache2
              sudo systemctl start apache2
            else
              echo "Apache ya está instalado."
            fi
            sudo mkdir -p /var/www/html
            sudo chown -R ${{ secrets.EC2_USER }} /var/www/html
            sudo chmod -R 755 /var/www/html
          debug: true

      - name: Deploy HTML file to AWS EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}        # IP pública de tu instancia EC2
          username: ${{ secrets.EC2_USER }}    # Usuario SSH, por ejemplo: ec2-user o ubuntu
          key: ${{ secrets.EC2_KEY }}          # Clave privada SSH desde los secretos de GitHub
          source: "./index.html"               # Fuente, que es el archivo HTML en tu repositorio
          target: "/var/www/html/index.html"   # Directorio destino en tu EC2

      - name: Restart Apache
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo systemctl restart apache2
          debug: true
