name: Deploy to EC2

on:
  push:
    branches:
      - main # Despliega solo cambios en la rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: deploy Apache
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 35.173.232.140
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /project
            sudo git pull https://github.com/DanisonEdiel/ec2-load-balancer-html.git
            sudo systemctl restart httpd
            git config --global --add safe.directory /project
          debug: true
      - name: deploy Apache
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 18.207.188.202
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /project
            sudo git pull https://github.com/DanisonEdiel/ec2-load-balancer-html.git
            sudo systemctl restart httpd
            git config --global --add safe.directory /project
          debug: true
