name: Deploy to EC2

on:
  push:
    branches:
      - main # Despliega solo cambios en la rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: deploy Apache
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 34.203.40.217
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /project
            sudo git pull https://github.com/DanisonEdiel/ec2-load-balancer-html.git
            sudo systemctl restart httpd
          debug: true
      - name: deploy Apache
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 52.207.249.42
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /project
            sudo git pull https://github.com/DanisonEdiel/ec2-load-balancer-html.git
            sudo systemctl restart httpd
          debug: true
